<a href="https://colab.research.google.com/github/Sank3t-Pand3y/Tensor-PyTorch/blob/main/Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import torch
print(torch.__version__)

2.8.0+cu126


In [62]:
if torch.cuda.is_available():
  print("GPU is available")
else:
  print("cuda is not available")

GPU is available


# Creating a Tensor

In [63]:
# using a empty
a = torch.empty(2,3)
a

tensor([[1.2198e-32, 0.0000e+00, 1.7365e-32],
        [0.0000e+00, 1.1483e+27, 4.2510e+21]])

In [64]:
 # check type
 type(a)

torch.Tensor

In [65]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [66]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [67]:
# torch.rand
torch.rand(2,3)

tensor([[0.7278, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])

In [68]:
# using manaul_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [69]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [70]:
# using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [71]:
#using linspace
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [72]:
# using eye i.e identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [73]:
# using full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes


In [74]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [75]:
x.shape

torch.Size([2, 3])

In [76]:
torch.empty_like(x)

tensor([[171798691851,            0,            0],
        [           0,            0,            0]])

In [77]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [78]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [79]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types


In [80]:
# find data types
x.dtype

torch.int64

In [81]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [82]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [83]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations on Tensors

In [84]:
c = torch.tensor([1,-2,3,-4])

In [85]:
# Absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [86]:
# negative of each item
torch.neg(c)

tensor([-1,  2, -3,  4])

In [87]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [88]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [89]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [90]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [91]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction Operation


In [92]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=float)
e

tensor([[8., 8., 4.],
        [4., 1., 0.]], dtype=torch.float64)

In [93]:
# sum
torch.sum(e)

tensor(25., dtype=torch.float64)

In [94]:
# sum along column
torch.sum(e, dim=0)

tensor([12.,  9.,  4.], dtype=torch.float64)

In [95]:
# sum along row
torch.sum(e, dim=1)

tensor([20.,  5.], dtype=torch.float64)

In [96]:
# mean
torch.mean(e)

tensor(4.1667, dtype=torch.float64)

In [97]:
# meadian
torch.median(e)

tensor(4., dtype=torch.float64)

In [98]:
# mean along column
torch.mean(e, dim=0)

tensor([6.0000, 4.5000, 2.0000], dtype=torch.float64)

In [99]:
# max and min
torch.max(e)

tensor(8., dtype=torch.float64)

In [100]:
# min
torch.min(e)

tensor(0., dtype=torch.float64)

In [101]:
# product
torch.prod(e)

tensor(0., dtype=torch.float64)

In [102]:
# standard deviation
torch.std(e)

tensor(3.3714, dtype=torch.float64)

In [103]:
# variance
torch.var(e)

tensor(11.3667, dtype=torch.float64)

In [104]:
# argmax
torch.argmax(e)

tensor(0)

In [105]:
# argmin
torch.argmin(e)

tensor(5)

# Matrix Operations

In [106]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[4, 3, 8],
        [7, 4, 6]])
tensor([[0, 1],
        [9, 9],
        [8, 0]])


In [107]:
# matrix multiplication
torch.matmul(f,g)

tensor([[91, 31],
        [84, 43]])

In [108]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [109]:
# transpose

torch.transpose(f,0,1)

tensor([[4, 7],
        [3, 4],
        [8, 6]])

In [110]:
h = torch.randint(size=(3,3), low = 0, high = 10, dtype = torch.float32)

In [111]:
h

tensor([[7., 0., 0.],
        [9., 5., 7.],
        [3., 9., 4.]])

In [112]:
# determinant
torch.det(h)

tensor(-301.)

In [113]:
# inverse
torch.inverse(h)

tensor([[ 0.1429,  0.0000,  0.0000],
        [ 0.0498, -0.0930,  0.1628],
        [-0.2193,  0.2093, -0.1163]])

# Comparison Operator

In [114]:
i = torch.randint(size = (2,3), low = 0, high = 10)
j = torch.randint(size=(2,3), low= 0 , high= 10)

print(i)
print(j)

tensor([[0, 5, 7],
        [5, 9, 9]])
tensor([[7, 5, 9],
        [8, 9, 7]])


In [115]:
# greater than
i > j

tensor([[False, False, False],
        [False, False,  True]])

In [118]:
# less than
i < j

tensor([[ True, False,  True],
        [ True, False, False]])

In [119]:
# equal to
i == j

tensor([[False,  True, False],
        [False,  True, False]])

In [120]:
# not equal to

i != j

tensor([[ True, False,  True],
        [ True, False,  True]])

# Special Function

In [121]:
k = torch.randint(size=(2,3), low = 0, high=10, dtype = torch.float32)
k

tensor([[9., 2., 6.],
        [7., 7., 8.]])

In [122]:
# log
torch.log(k)

tensor([[2.1972, 0.6931, 1.7918],
        [1.9459, 1.9459, 2.0794]])

In [123]:
# exponents
torch.exp(k)

tensor([[8.1031e+03, 7.3891e+00, 4.0343e+02],
        [1.0966e+03, 1.0966e+03, 2.9810e+03]])

In [124]:
# square root
torch.sqrt(k)

tensor([[3.0000, 1.4142, 2.4495],
        [2.6458, 2.6458, 2.8284]])

In [125]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.8808, 0.9975],
        [0.9991, 0.9991, 0.9997]])

In [126]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.8808, 0.0067, 0.1192],
        [0.1192, 0.9933, 0.8808]])

In [127]:
#relu
torch.relu(k)

tensor([[9., 2., 6.],
        [7., 7., 8.]])

# Inplace Operations

In [128]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3687, 0.9053, 0.8356],
        [0.3039, 0.6726, 0.5740]])
tensor([[0.9233, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])


In [129]:
m.add_(n)
m

tensor([[1.2920, 1.8231, 1.5946],
        [1.0814, 1.2905, 0.9118]])

In [130]:
m.relu_()

tensor([[1.2920, 1.8231, 1.5946],
        [1.0814, 1.2905, 0.9118]])

# Copying a Tensor

In [131]:
a_new = torch.rand(2,3)
a_new

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])

In [132]:
b_new = a_new.clone()

In [133]:
a_new [0][0] = 10
a_new

tensor([[10.0000,  0.9454,  0.7116],
        [ 0.1157,  0.6574,  0.3451]])

In [134]:
b_new

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])

In [135]:
id(a_new)

132248190085360

In [136]:
id(b_new)

132252562480240