<a href="https://colab.research.google.com/github/Sank3t-Pand3y/Tensor-PyTorch/blob/main/Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import torch
print(torch.__version__)

2.8.0+cu126


In [47]:
if torch.cuda.is_available():
  print("GPU is available")
else:
  print("cuda is not available")

GPU is available


# Creating a Tensor

In [48]:
# using a empty
a = torch.empty(2,3)
a

tensor([[3.3874e+05, 0.0000e+00, 4.2404e+05],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [49]:
 # check type
 type(a)

torch.Tensor

In [50]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [51]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [52]:
# torch.rand
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [53]:
# using manaul_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [54]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [55]:
# using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [56]:
#using linspace
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [57]:
# using eye i.e identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [58]:
# using full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])