<a href="https://colab.research.google.com/github/Sank3t-Pand3y/Tensor-PyTorch/blob/main/Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
else:
  print("cuda is not available")

GPU is available


# Creating a Tensor

In [3]:
# using a empty
a = torch.empty(2,3)
a

tensor([[0.0000e+00, 0.0000e+00, 3.9371e-31],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
 # check type
 type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# torch.rand
torch.rand(2,3)

tensor([[0.6469, 0.7590, 0.9972],
        [0.7444, 0.3503, 0.1827]])

In [8]:
# using manaul_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [11]:
#using linspace
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [12]:
# using eye i.e identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
# using full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes


In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types


In [20]:
# find data types
x.dtype

torch.int64

In [21]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations on Tensors

In [24]:
c = torch.tensor([1,-2,3,-4])

In [25]:
# Absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [26]:
# negative of each item
torch.neg(c)

tensor([-1,  2, -3,  4])

In [27]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [28]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [29]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [30]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [31]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])